# Site settings
title:
email: info@crossfitulladulla.com
url: http://crossfitulladulla.com
description: ""

#baseurl: /

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#042037'
  contrast-1: '#123552'
  contrast-2: '#2A4F6E'
  contrast-3: '#496C89'
  links: '#718DA5'

# Footer settings
footer: Southern Martial Arts

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/SouthernMartialArts/

# Build settings
markdown: kramdown
permalink: pretty
